In [8]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

x = torch.rand(5,3)
print(x)

a = torch.zeros(2,3)
b = torch.ones(2,3)
c = torch.randn(2,3)
print(a,b,c)
print(a+b+c)
print(b * c)
print(a.shape)

tensor_requires_grad = torch.tensor([1.0], requires_grad=True)

# 进行一些操作
tensor_result = tensor_requires_grad * 2

# 计算梯度
tensor_result.backward()
print(tensor_requires_grad.grad)  # 输出梯度

2.6.0+cu124
False
tensor([[0.6424, 0.5518, 0.1051],
        [0.5273, 0.2051, 0.0969],
        [0.8251, 0.6165, 0.7288],
        [0.6454, 0.4644, 0.5800],
        [0.8111, 0.1365, 0.8772]])
tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[-0.2141,  1.7086,  0.7178],
        [-0.5088,  1.1844, -0.8464]])
tensor([[0.7859, 2.7086, 1.7178],
        [0.4912, 2.1844, 0.1536]])
tensor([[-0.2141,  1.7086,  0.7178],
        [-0.5088,  1.1844, -0.8464]])
torch.Size([2, 3])
tensor([2.])


In [ ]:
import torch.nn as nn
import torch.optim as optim

class SimpleNN(nn.Module):
  def __init__(self):
    super(SimpleNN,self).__init()
    self.fc1 = nn.Linear(2,2)
    self.fc2 = nn.Linear(2,1)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    x = self.fc2(x)
    return x

model = SimpleNN()
print(model)