In [19]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.rand(5,3) #创建一个服从均匀分布的随机张量，值在 [0, 1)。
print(x)

a = torch.zeros(2,3)
b = torch.ones(2,3)
c = torch.randn(2,3) #创建一个服从正态分布的随机张量，均值为 0，标准差为 1。
d = torch.arange(1,10,3) #创建一个一维序列张量,start,end,step
e = torch.linspace(1,9,6) #创建一个在指定范围内等间隔的序列张量。
f = torch.eye(3) #创建一个单位矩阵（对角线为 1，其他为 0）。
g = torch.tensor([[1,2,3],[2,3,4],[4,5,6]])
print(a,b,c)
print(a+b+c)
print(b * c)
print(a.shape)
print(d,e)
print(g)
print(g.mT) # x.mT is equivalent to x.transpose(-2, -1).

tensor_requires_grad = torch.tensor([1.0], requires_grad=True)

# 进行一些操作
tensor_result = tensor_requires_grad * 2

# 计算梯度
tensor_result.backward()
print(tensor_requires_grad.grad)  # 输出梯度

2.6.0+cu124
False
tensor([[0.6312, 0.6904, 0.8570],
        [0.8477, 0.0056, 0.2654],
        [0.9901, 0.5780, 0.0797],
        [0.7979, 0.1772, 0.6092],
        [0.4524, 0.4592, 0.9932]])
tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[ 1.3319, -0.3214,  0.9812],
        [ 0.1165, -1.5420, -2.0866]])
tensor([[ 2.3319,  0.6786,  1.9812],
        [ 1.1165, -0.5420, -1.0866]])
tensor([[ 1.3319, -0.3214,  0.9812],
        [ 0.1165, -1.5420, -2.0866]])
torch.Size([2, 3])
tensor([1, 4, 7]) tensor([1.0000, 2.6000, 4.2000, 5.8000, 7.4000, 9.0000])
tensor([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]])
tensor([[1, 2, 4],
        [2, 3, 5],
        [3, 4, 6]])
tensor([2.])


In [11]:
import torch.nn as nn
import torch.optim as optim

class SimpleNN(nn.Module):
  def __init__(self):
    super(SimpleNN,self).__init__()
    self.fc1 = nn.Linear(2,2)
    self.fc2 = nn.Linear(2,1)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    x = self.fc2(x)
    return x

model = SimpleNN()

# 定义损失函数和优化器
criterion = nn.MSELoss() # 均方误差损失函数
optimizer = optim.Adam(model.parameters(),lr=0.001) #Adam优化器

X = torch.randn(10,2) #10个样本，2个特征
Y = torch.randn(10,1) # 10个目标值

# 训练循环
for epoch in range(100): #训练100轮
  optimizer.zero_grad() #清空之前的梯度
  output = model(X) #前向传播
  loss = criterion(output, Y) #计算损失
  loss.backward() #反向传播
  optimizer.step() #更新参数

  if (epoch+1) % 10 == 0:
    print(f'Epoch [{epoch+1}/100],Loss: {loss.item():.4f}')


Epoch [10/100],Loss: 0.4096
Epoch [20/100],Loss: 0.3979
Epoch [30/100],Loss: 0.3871
Epoch [40/100],Loss: 0.3771
Epoch [50/100],Loss: 0.3679
Epoch [60/100],Loss: 0.3595
Epoch [70/100],Loss: 0.3517
Epoch [80/100],Loss: 0.3442
Epoch [90/100],Loss: 0.3369
Epoch [100/100],Loss: 0.3299


In [29]:
tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
print("orign:\n",tensor)

# 1. **索引和切片操作**
print("\n【索引和切片】")
print("first line:",tensor[0])
print("first line, first cloum:",tensor[0,0])
print(tensor[:,1]) # 获取第二列所有元素

# 2. **形状变换操作**
print("\n【形状变换】")
reshaped = tensor.view(3,2) # 改变张量形状为 3x2
print(reshaped)
flattened = tensor.flatten() # 将张量展平成一维
print(flattened)

# 3. **数学运算操作**
print("\n【数学运算】")
tensor_add = tensor + 10
print('add:',tensor_add)
tensor_mul = tensor * 2
print('mul:',tensor_mul)
tensor_sum = tensor.sum()
print('sum:',tensor_sum)

# 4. **与其他张量的操作**
print("\n【与其他张量操作】")
tensor2 = torch.tensor([[1,1,1],[2,2,2]],dtype=torch.float32)
print('tensor2:',tensor2)
tensor_dot = torch.matmul(tensor,tensor2.t())
print('matmul:',tensor_dot)

# 5. **条件判断和筛选**
print("\n【条件判断和筛选】")
mask = tensor > 3
print('mask:',mask)
filter_tensor = tensor[tensor > 4]
print('filter:',filter_tensor)

orign:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

【索引和切片】
first line: tensor([1., 2., 3.])
first line, first cloum: tensor(1.)
tensor([2., 5.])

【形状变换】
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([1., 2., 3., 4., 5., 6.])

【数学运算】
add: tensor([[11., 12., 13.],
        [14., 15., 16.]])
mul: tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
sum: tensor(21.)

【与其他张量操作】
tensor2: tensor([[1., 1., 1.],
        [2., 2., 2.]])
matmul: tensor([[ 6., 12.],
        [15., 30.]])

【条件判断和筛选】
mask: tensor([[False, False, False],
        [ True,  True,  True]])
filter: tensor([5., 6.])


前馈神经网络（Feedforward Neural Network，FNN）
前馈神经网络（Feedforward Neural Network，FNN）是神经网络家族中的基本单元。

前馈神经网络特点是数据从输入层开始，经过一个或多个隐藏层，最后到达输出层，全过程没有循环或反馈。

循环神经网络（Recurrent Neural Network, RNN）
循环神经网络（Recurrent Neural Network, RNN）络是一类专门处理序列数据的神经网络，能够捕获输入数据中时间或顺序信息的依赖关系。

RNN 的特别之处在于它具有"记忆能力"，可以在网络的隐藏状态中保存之前时间步的信息。

循环神经网络用于处理随时间变化的数据模式。

在 RNN 中，相同的层被用来接收输入参数，并在指定的神经网络中显示输出参数。

PyTorch 提供了许多常见的神经网络层，以下是几个常见的：

nn.Linear(in_features, out_features)：全连接层，输入 in_features 个特征，输出 out_features 个特征。
nn.Conv2d(in_channels, out_channels, kernel_size)：2D 卷积层，用于图像处理。
nn.MaxPool2d(kernel_size)：2D 最大池化层，用于降维。
nn.ReLU()：ReLU 激活函数，常用于隐藏层。
nn.Softmax(dim)：Softmax 激活函数，通常用于输出层，适用于多类分类问题。


激活函数（Activation Function）
激活函数决定了神经元是否应该被激活。它们是非线性函数，使得神经网络能够学习和执行更复杂的任务。常见的激活函数包括：

Sigmoid：用于二分类问题，输出值在 0 和 1 之间。
Tanh：输出值在 -1 和 1 之间，常用于输出层之前。
ReLU（Rectified Linear Unit）：目前最流行的激活函数之一，定义为 f(x) = max(0, x)，有助于解决梯度消失问题。
Softmax：常用于多分类问题的输出层，将输出转换为概率分布。

损失函数（Loss Function）
损失函数用于衡量模型的预测值与真实值之间的差异。

常见的损失函数包括：

均方误差（MSELoss）：回归问题常用，计算输出与目标值的平方差。
交叉熵损失（CrossEntropyLoss）：分类问题常用，计算输出和真实标签之间的交叉熵。
BCEWithLogitsLoss：二分类问题，结合了 Sigmoid 激活和二元交叉熵损失。

优化器（Optimizer）
优化器负责在训练过程中更新网络的权重和偏置。

常见的优化器包括：

SGD（随机梯度下降）
Adam（自适应矩估计）
RMSprop（均方根传播）

训练过程（Training Process）
训练神经网络涉及以下步骤：

准备数据：通过 DataLoader 加载数据。
定义损失函数和优化器。
前向传播：计算模型的输出。
计算损失：与目标进行比较，得到损失值。
反向传播：通过 loss.backward() 计算梯度。
更新参数：通过 optimizer.step() 更新模型的参数。
重复上述步骤，直到达到预定的训练轮数。

测试与评估
训练完成后，需要对模型进行测试和评估。

常见的步骤包括：

计算测试集的损失：测试模型在未见过的数据上的表现。
计算准确率（Accuracy）：对于分类问题，计算正确预测的比例。


神经网络类型
前馈神经网络（Feedforward Neural Networks）：数据单向流动，从输入层到输出层，无反馈连接。
卷积神经网络（Convolutional Neural Networks, CNNs）：适用于图像处理，使用卷积层提取空间特征。
循环神经网络（Recurrent Neural Networks, RNNs）：适用于序列数据，如时间序列分析和自然语言处理，允许信息反馈循环。
长短期记忆网络（Long Short-Term Memory, LSTM）：一种特殊的RNN，能够学习长期依赖关系。

In [31]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# 自定义数据集类
class MyDataset(Dataset):
    def __init__(self, X_data, Y_data):
        """
        初始化数据集，X_data 和 Y_data 是两个列表或数组
        X_data: 输入特征
        Y_data: 目标标签
        """
        self.X_data = X_data
        self.Y_data = Y_data

    def __len__(self):
        """返回数据集的大小"""
        return len(self.X_data)

    def __getitem__(self, idx):
        """返回指定索引的数据"""
        x = torch.tensor(self.X_data[idx], dtype=torch.float32)  # 转换为 Tensor
        y = torch.tensor(self.Y_data[idx], dtype=torch.float32)
        return x, y

# 示例数据
X_data = [[1, 2], [3, 4], [5, 6], [7, 8]]  # 输入特征
Y_data = [1, 0, 1, 0]  # 目标标签

# 创建数据集实例
dataset = MyDataset(X_data, Y_data)

# 创建 DataLoader 实例，batch_size 设置每次加载的样本数量
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# 打印加载的数据
for epoch in range(1):
    for batch_idx, (inputs, labels) in enumerate(dataloader):
        print(f'Batch {batch_idx + 1}:')
        print(f'Inputs: {inputs}')
        print(f'Labels: {labels}')

Batch 1:
Inputs: tensor([[5., 6.],
        [3., 4.]])
Labels: tensor([1., 0.])
Batch 2:
Inputs: tensor([[1., 2.],
        [7., 8.]])
Labels: tensor([1., 0.])
